name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: 
      - completed

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ["dev"]

    defaults:
      run:
        shell: bash

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      TF_VAR_project: ${{ secrets.GCP_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Branch Name
        uses: nelonoel/branch-name@v1.0.1

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ${{ matrix.dir }}:
              - 'terraform/${{ matrix.dir }}/**'

      - name: Setup Terraform
        if: steps.changes.outputs.${{ matrix.dir }} == 'true'
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        if: steps.changes.outputs.${{ matrix.dir }} == 'true'
        run: terraform init
        working-directory: terraform/${{ matrix.dir }} 

      - name: Terraform Plan
        if: steps.changes.outputs.${{ matrix.dir }} == 'true'
        run: terraform plan
        working-directory: terraform/${{ matrix.dir }}

      - name: Terraform Apply
        if: |
          steps.changes.outputs.${{ matrix.dir }} == 'true' &&
          BRANCH_NAME == "main" && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform/${{ matrix.dir }}
