name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: fetcher

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Go Dependencies
      run: go mod download
    
    - name: Install Firestore Emulator
      run: sudo apt-get install -y google-cloud-sdk-firestore-emulator

    - name: Test
      run: go test -v .
